[uart.1]
serial_port = "/dev/ttyUSB0"
nos_bus = "usart_1"

[uart.0]
serial_port = "/dev/ttyUSB0"
nos_bus = "usart_0"

[i2c.0]
device_path = "/dev/i2c-0"
slave_address = 43
nos_bus = "i2c_0"
nos_slave_addr = 8

[i2c.1]
device_path = "/dev/i2c-1"
slave_address = 44
nos_bus = "i2c_0"
nos_slave_addr = 8

[i2c.2]
device_path = "/dev/i2c-1"
slave_address = 44
nos_bus = "i2c_0"
nos_slave_addr = 8